FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

ENV TZ='Asia/Tokyo'

# USER vscode
# WORKDIR /home/vscode
# RUN wget https://raw.githubusercontent.com/kitakou0313/dotfiles/main/installer.sh && chmod 777 installer.sh
# RUN bash installer.sh